# Generated by Django 4.0.3 on 2022-07-01 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import util.conversion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AS',
            fields=[
                ('iaid', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[util.conversion._ia_validator], verbose_name='The IA id like 1-ff00:1:1')),
                ('certificate_pem', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AS in the IXP',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pem', models.TextField()),
                ('key_pem', models.TextField()),
            ],
            options={
                'verbose_name': 'Broker is the IXP',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaid', models.CharField(max_length=255, validators=[util.conversion._ia_validator], verbose_name='The IA id like 1-ff00:1:1')),
                ('is_core', models.BooleanField()),
                ('signature', models.BinaryField()),
                ('notbefore', models.DateTimeField()),
                ('notafter', models.DateTimeField()),
                ('reachable_paths', models.TextField(blank=True)),
                ('qos_class', models.IntegerField()),
                ('price_per_unit', models.FloatField()),
                ('bw_profile', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('br_address_template', models.TextField()),
                ('br_mtu', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(65534)])),
                ('br_link_to', models.CharField(choices=[('CORE', 'CORE'), ('PARENT', 'PARENT'), ('PEER', 'PEER')], max_length=10)),
                ('deprecates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deprecated_by', to='market.offer')),
            ],
            options={
                'verbose_name': 'Bandwidth Offer by AS',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.BinaryField()),
                ('bw_profile', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('starting_on', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.as')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='market.offer')),
            ],
            options={
                'verbose_name': 'Signed Purchase Order',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('signature_broker', models.BinaryField()),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='market.purchaseorder')),
            ],
            options={
                'verbose_name': 'Contract',
            },
        ),
    ]
