# Generated by Django 4.0.3 on 2022-05-06 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaid', models.BigIntegerField()),
                ('iscore', models.BooleanField()),
                ('signature', models.BinaryField()),
                ('notbefore', models.DateTimeField()),
                ('notafter', models.DateTimeField()),
                ('reachable_paths', models.TextField()),
                ('qos_class', models.IntegerField()),
                ('price_per_nanounit', models.IntegerField()),
                ('bw_profile', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
            ],
            options={
                'verbose_name': 'Bandwidth Offer by AS',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.BigIntegerField()),
                ('signature', models.BinaryField()),
                ('bw_profile', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('starting_on', models.DateTimeField()),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='market.offer')),
            ],
            options={
                'verbose_name': 'Signed Purchase Order',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('signature_broker', models.BinaryField()),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='market.purchaseorder')),
            ],
            options={
                'verbose_name': 'Contract',
            },
        ),
    ]
