# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\x12\x06market\x1a\x1bgoogle/protobuf/empty.proto\"\r\n\x0bListRequest\"&\n\x05Offer\x12\x0c\n\x04iaid\x18\x01 \x01(\x03\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t2F\n\x10MarketController\x12\x32\n\nListOffers\x12\x13.market.ListRequest\x1a\r.market.Offer\"\x00\x62\x06proto3')



_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_OFFER = DESCRIPTOR.message_types_by_name['Offer']
ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'market_pb2'
  # @@protoc_insertion_point(class_scope:market.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

Offer = _reflection.GeneratedProtocolMessageType('Offer', (_message.Message,), {
  'DESCRIPTOR' : _OFFER,
  '__module__' : 'market_pb2'
  # @@protoc_insertion_point(class_scope:market.Offer)
  })
_sym_db.RegisterMessage(Offer)

_MARKETCONTROLLER = DESCRIPTOR.services_by_name['MarketController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTREQUEST._serialized_start=53
  _LISTREQUEST._serialized_end=66
  _OFFER._serialized_start=68
  _OFFER._serialized_end=106
  _MARKETCONTROLLER._serialized_start=108
  _MARKETCONTROLLER._serialized_end=178
# @@protoc_insertion_point(module_scope)
