# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_pb2 as market__pb2


class MarketControllerStub(object):
    """TODO(juagargi) the data types used allow easy integration with the ones from Django.
    Despite this, we need to change them here to be more adequate. E.g. change
    Offer.bw_profile from a string to a repeated int32

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListOffers = channel.unary_unary(
                '/market.MarketController/ListOffers',
                request_serializer=market__pb2.ListRequest.SerializeToString,
                response_deserializer=market__pb2.Offer.FromString,
                )


class MarketControllerServicer(object):
    """TODO(juagargi) the data types used allow easy integration with the ones from Django.
    Despite this, we need to change them here to be more adequate. E.g. change
    Offer.bw_profile from a string to a repeated int32

    """

    def ListOffers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListOffers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOffers,
                    request_deserializer=market__pb2.ListRequest.FromString,
                    response_serializer=market__pb2.Offer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market.MarketController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketController(object):
    """TODO(juagargi) the data types used allow easy integration with the ones from Django.
    Despite this, we need to change them here to be more adequate. E.g. change
    Offer.bw_profile from a string to a repeated int32

    """

    @staticmethod
    def ListOffers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketController/ListOffers',
            market__pb2.ListRequest.SerializeToString,
            market__pb2.Offer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
